# -*- coding: utf-8 -*-
"""question1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIYFOUozZhKvQsCtBCPpIrOSjQ_aPht-

**Question 1**:

Can we predict whether a game will receive a positive or negative review based on its price, playtime, CCU, and ratings, using classification models (LinearRegression & KNN Regression)?
"""

# imports
import pandas as pd
import requests
import numpy as np
import kagglehub
import os
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error

import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

path = kagglehub.dataset_download("artermiloff/steam-games-dataset")
raw_df = pd.read_csv(os.path.join(path, "games_march2025_cleaned.csv"))

columns = ['appid', 'name', 'release_date', 'price', 'genres', 'positive',
            'negative', 'num_reviews_total', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks',
            'peak_ccu']

df = raw_df[columns]
df

df = raw_df[columns].copy()
df = df.dropna(subset=['price', 'positive', 'negative', 'average_playtime_forever', 'peak_ccu'])


df = df[(df['positive'] + df['negative']) > 0]

# Create binary review score: 1 = mostly positive, 0 = mixed/negative
df['review_score_binary'] = (df['positive'] / (df['positive'] + df['negative']) >= 0.7).astype(int)

# select features
X = df[['price', 'average_playtime_forever', 'peak_ccu', 'positive', 'negative']]
y = df['review_score_binary']

# train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# logistic regression model
logreg_pipeline = make_pipeline(
    StandardScaler(),
    LogisticRegression()
)

logreg_pipeline.fit(X_train, y_train)
logreg_preds = logreg_pipeline.predict(X_test)

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, logreg_preds))
print("Confusion Matrix:\n", confusion_matrix(y_test, logreg_preds))

knn_pipeline = make_pipeline(
    StandardScaler(),
    KNeighborsClassifier()
)

param_grid = {
    'kneighborsclassifier__n_neighbors': list(range(3, 10)),
    'kneighborsclassifier__metric': ['euclidean', 'manhattan']
}

grid = GridSearchCV(knn_pipeline, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

best_knn = grid.best_estimator_
knn_preds = best_knn.predict(X_test)

print("\nKNN Classifier")
print("Best Params:", grid.best_params_)
print("Accuracy:", accuracy_score(y_test, knn_preds))
print("Confusion Matrix:\n", confusion_matrix(y_test, knn_preds))

import matplotlib.pyplot as plt

# store accuracies
logreg_accuracy = accuracy_score(y_test, logreg_preds)
knn_accuracy = accuracy_score(y_test, knn_preds)

# plotting
plt.figure(figsize=(6, 4))
plt.bar(['Logistic Regression', 'Best KNN Model'], [logreg_accuracy, knn_accuracy], color=['steelblue', 'seagreen'])
plt.ylim(0, 1)
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy')
plt.show()