# -*- coding: utf-8 -*-
"""question 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCIXJyNBeD3Ya0nuQS7H-yzczpYctnII
"""

import pandas as pd
import requests
import numpy as np
import kagglehub
import os
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error

import matplotlib.pyplot as plt

path = kagglehub.dataset_download("artermiloff/steam-games-dataset")
raw_df = pd.read_csv(os.path.join(path, "games_march2025_cleaned.csv"))

columns = ['appid', 'name', 'release_date', 'price', 'genres', 'positive',
            'negative', 'num_reviews_total', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks',
            'peak_ccu']

df = raw_df[columns]

df.head(50)

### extract year from release date

# df['release_year'] = df['release_date'].str[:4] # gives a warning
df.loc[:, 'release_year'] = df['release_date'].str[:4].astype(int)

# get mean estimated owners
df.loc[:, 'mean_est_owners'] = df['estimated_owners'].str.split('-').apply(lambda x : (int(x[0]) + int(x[1]))/2)


# new df of useful features
features = ['name', 'release_year', 'mean_est_owners', 'price', 'average_playtime_forever']
df_features = df[features]

# df_features.head(50)

### training sets

X = df_features[['mean_est_owners', 'price', 'average_playtime_forever']]
y = df_features[['release_year']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=67)

# create models

# linear regression
ln_model = LinearRegression()

# for visualizing later
ln_pipeline = make_pipeline(StandardScaler(), ln_model)
# ln_pipeline.fit(X_train, y_train)
# ln_pred = ln_pipeline.predict(X_test)

ln_scores = -cross_val_score(ln_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error')
ln_rmse = round(ln_scores.mean(), 3)
print(f"Linear Regression RMSE: {ln_rmse}")

# knn (with hyperparameter tuning)


knn_model = KNeighborsRegressor()
knn_pipeline = make_pipeline(StandardScaler(), knn_model)

# WARNING: GRIDSEARCH TAKES VERY LONG TIME TO RUN (like at least 2 minutes)
knn_grid = GridSearchCV(
    knn_pipeline,
    param_grid={
        'kneighborsregressor__n_neighbors': range(5, 20),
        'kneighborsregressor__metric': ['euclidean', 'manhattan']
    },
    scoring='neg_mean_squared_error',
    cv=5
)

knn_grid.fit(X_train, y_train)

"""
range of (5, 19)

knn_grid.best_params_ =
{'kneighborsregressor__metric': 'euclidean',
 'kneighborsregressor__n_neighbors': 19}
"""

# knn_grid.best_params_

### RMSE of KNN

best_knn_pipeline = knn_grid.best_estimator_
knn_pred = best_knn_pipeline.predict(X_test)
knn_rmse = round(root_mean_squared_error(y_test, knn_pred), 3)

print(f"KNN root mean squared error: {knn_rmse}")

# parameters of best KNN model
knn_grid.best_params_

print(f"Linear Regression RMSE: {ln_rmse}")
print(f"KNN root mean squared error: {knn_rmse}")

rmse_labels = ['Linear Regression', 'KNN']
rmse_vals = [ln_rmse, knn_rmse]
rmse_color = ['lightcoral', 'skyblue']

plt.bar(rmse_labels, rmse_vals, color=rmse_color)
plt.ylabel('RMSE')
plt.title('Linear Regression vs. KNN for Predicting Game Year Release')

plt.text(0, rmse_vals[0], rmse_vals[0], ha='center', va='bottom')
plt.text(1, rmse_vals[1], rmse_vals[1], ha='center', va='bottom')

plt.show()