# -*- coding: utf-8 -*-
"""rohan group proj colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxVLScNcbz-dXjWLgM63O-hmo7b3a2Vl

**Question 3**:

Can we predict the number of concurrent users (CCU) a game will have based on its features?
"""

from kagglehub import kagglehub
import pandas as pd
import os
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_transformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import make_pipeline


path = kagglehub.dataset_download("artermiloff/steam-games-dataset")
raw_df = pd.read_csv(os.path.join(path, "games_march2025_cleaned.csv"))

# select columns
columns = ['appid', 'name', 'release_date', 'price', 'genres', 'positive',
           'negative', 'num_reviews_total', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks',
           'peak_ccu']
df = raw_df[columns].copy()

# fix estimated_owners to be numeric
df['estimated_owners'] = df['estimated_owners'].str.split('-').apply(lambda x: (int(x[0]) + int(x[1])) / 2)

# convert release_date to datetime and extract parts
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')  # Handle errors safely
df['release_year'] = df['release_date'].dt.year
df['release_month'] = df['release_date'].dt.month
df['release_dayofweek'] = df['release_date'].dt.dayofweek

# drop the original release_date column
df.drop(columns=['release_date'], inplace=True)

# define features
features = ['release_year', 'release_month', 'release_dayofweek', 'price', 'genres',
            'positive', 'negative', 'num_reviews_total', 'estimated_owners',
            'average_playtime_forever', 'average_playtime_2weeks']

# train/test split
X_train, X_test, y_train, y_test = train_test_split(df[features], df['peak_ccu'], test_size=0.2, random_state=42)

# separate numerical and categorical
numeric_features = ['release_year', 'release_month', 'release_dayofweek', 'price', 'positive',
                    'negative', 'num_reviews_total', 'estimated_owners', 'average_playtime_forever',
                    'average_playtime_2weeks']
categorical_features = ['genres']

# preprocessor
preprocessor = make_column_transformer(
    (StandardScaler(), numeric_features),
    (OneHotEncoder(handle_unknown='ignore'), categorical_features)
)

# lr pipeline
lr_pipeline = make_pipeline(
    preprocessor,
    LinearRegression()
)

# train
lr_pipeline.fit(X_train, y_train)
y_pred_lr = lr_pipeline.predict(X_test)

# evaluation
lr_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr))
lr_mae = mean_absolute_error(y_test, y_pred_lr)

# errors
print(f"RMSE: {lr_rmse}")
print(f"MAE: {lr_mae}")

# knn pipeline
knn_pipeline = make_pipeline(
    preprocessor,
    KNeighborsRegressor()
)

# getting different models of knn
param_grid = {
    "kneighborsregressor__n_neighbors": list(range(1, 11)),
    "kneighborsregressor__metric": ["euclidean", "manhattan"]
}

# grid search
grid_search = GridSearchCV(
    knn_pipeline,
    param_grid,
    cv=3,
    scoring="neg_mean_squared_error",
    n_jobs=-1)

grid_search.fit(X_train, y_train)

# finding best knn model
print(f"Best Params: {grid_search.best_params_}")

# predicting using best knn model
best_knn = grid_search.best_estimator_
y_pred_knn = best_knn.predict(X_test)

# finding errors
knn_rmse = np.sqrt(mean_squared_error(y_test, y_pred_knn))
knn_mae = mean_absolute_error(y_test, y_pred_knn)

# errors
print(f"RMSE: {knn_rmse}")
print(f"MAE:  {knn_mae}")

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
plt.bar(['Linear Regression', 'KNN'], [lr_rmse, knn_rmse], color=['skyblue', 'orange'])
plt.title('RMSE Comparison')
plt.ylabel('Root Mean Squared Error')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
plt.bar(['KNN', 'Linear Regression'], [lr_mae, knn_mae], color=['skyblue', 'orange'])
plt.title('MAE Comparison')
plt.ylabel('Root Mean Squared Error')
plt.tight_layout()
plt.show()