# -*- coding: utf-8 -*-
"""question 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mauo7u-fzTqoo0Bg-Qs_VDrQ0TD3dmzf

**Question 4**:

Can we predict the total number of owners a game has based on its reviews, price, and genre?
"""

# imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, mean_squared_error
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, KFold
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error
import kagglehub
import kagglehub
from kagglehub import KaggleDatasetAdapter
import os
import csv

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from matplotlib.colors import LogNorm

path = kagglehub.dataset_download("artermiloff/steam-games-dataset")
raw_df = pd.read_csv(os.path.join(path, "games_march2025_cleaned.csv"))

columns = ['appid', 'name', 'release_date', 'price', 'genres', 'positive',
            'negative', 'num_reviews_total', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks',
            'peak_ccu', 'mac', 'windows', 'linux']

df = raw_df[columns]

df['estimated_owners'] = raw_df['estimated_owners'].str.split('-').apply(lambda x : (int(x[0]) + int(x[1]))/2)

df = df.head(50)


df

numeric_columns = df[['price', 'genres', 'peak_ccu', 'estimated_owners', 'negative', 'positive']]

bool_columns = df[['windows', 'linux', 'mac']]
bool_columns = bool_columns.copy()
bool_columns['windows'] = df['windows'].map({False: 0, True: 1})
bool_columns['mac'] = df['mac'].map({False: 0, True: 1})
bool_columns['linux'] = df['linux'].map({False: 0, True: 1})

bool_columns

filtered_df = numeric_columns.merge(bool_columns, left_index=True, right_index=True)
filtered_df = filtered_df.dropna(subset=['genres', 'peak_ccu', 'negative', 'positive', 'windows', 'mac', 'linux', 'estimated_owners'])

"""##KNearest Neighbors Model"""

# define features and target
X = filtered_df[['genres', 'peak_ccu', 'negative', 'positive', 'windows', 'mac', 'linux']]
y = filtered_df['estimated_owners']

# train-test split (using smaller test size for more training data)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# column transformer
preprocessor = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore', sparse_output=True), ['genres']),  # sparse output
    (StandardScaler(), ['peak_ccu', 'negative', 'positive', 'windows', 'mac', 'linux']),
    remainder='passthrough'
)

# create pipeline
pipeline = make_pipeline(
    preprocessor,
    KNeighborsRegressor()
)

# define parameter grid
param_grid = {
    'kneighborsregressor__n_neighbors': range(1,20),
    'kneighborsregressor__metric': ['euclidean','manhattan'],
}

# grid search
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring='neg_mean_squared_error',
    cv=3
)

grid_search.fit(X_train, y_train)

# print best parameters
print("\nBest parameters found:")
print(grid_search.best_params_)

# evaluate on training set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# calculate metrics
rmse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print("KNN RMSE: ", round(rmse))
print("KNN MAE: ", round(mae))

"""##Linear Regression Model"""

# define features and target
X = filtered_df[['genres', 'peak_ccu', 'negative', 'positive', 'windows', 'mac', 'linux']]
y = filtered_df['estimated_owners']

# train-test split (using smaller test size for more training data)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# preprocessing pipeline with sparse matrices to save memory
preprocessor = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore', sparse_output=True), ['genres']),  # Sparse output
    (StandardScaler(), ['peak_ccu', 'negative', 'positive', 'windows', 'mac', 'linux']),
    remainder='passthrough'
)

# create pipeline
pipeline2 = make_pipeline(
    preprocessor,
    LinearRegression()
)

pipeline2.fit(X_train, y_train)

y_pred2 = pipeline2.predict(X_test)

# calculate metrics
rmse2 = mean_squared_error(y_test, y_pred2)
mae2 = mean_absolute_error(y_test, y_pred2)
print("LR RMSE: ", round(rmse2))
print("LR MAE: ", round(mae2))

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
plt.bar(['KNN', 'Linear Regression'], [rmse, rmse2], color=['skyblue', 'orange'])
plt.title('RMSE Comparison (Scale: 1e15)')
plt.ylabel('Root Mean Squared Error')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
plt.bar(['KNN', 'Linear Regression'], [mae, mae2], color=['skyblue', 'orange'])
plt.title('MAE Comparison (Scale: 1e7)')
plt.ylabel('Mean Absolute Error')
plt.tight_layout()
plt.show()

