# -*- coding: utf-8 -*-
"""question 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h794lLDk8-ZUXdr7L1PolheVH0oGIkW_
"""

### imports

import pandas as pd
import requests
import numpy as np
import kagglehub
import os
import numpy as np

# genres are string representation for some reason?
import ast

from sklearn.neighbors import KNeighborsRegressor

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MultiLabelBinarizer

from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error

import matplotlib.pyplot as plt

path = kagglehub.dataset_download("artermiloff/steam-games-dataset")
raw_df = pd.read_csv(os.path.join(path, "games_march2025_cleaned.csv"))

columns = ['appid', 'name', 'release_date', 'price', 'genres', 'positive',
            'negative', 'num_reviews_total', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks',
            'peak_ccu']

df = raw_df[columns]

features = ['name', 'price', 'genres', 'num_reviews_total']
df_features = df[features]

X = df_features[['genres', 'price']]
y = df_features[['num_reviews_total']]

X['genres'] = X['genres'].apply(ast.literal_eval) # list of genres are in string representation for some reason so this converts to a list

### MultiLabelBinarizer and StandardScaler applied separately for preprocessing the data

mlb = MultiLabelBinarizer()
genres_mlb = pd.DataFrame(mlb.fit_transform(X['genres']), columns=mlb.classes_)

scaler = StandardScaler()
nums_scale = pd.DataFrame(scaler.fit_transform(X[['price']]), columns=['price'])

# concatenating the new preprocessed columns together
X_new = pd.concat([genres_mlb, nums_scale], axis=1)


X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=67)

### training the KNN model

### WARNING: THIS TAKES LIKE 7 MINUTES TO RUN
ks = range(1, 15)
rmse_scores = []

for k in ks:
    knn_model = KNeighborsRegressor(n_neighbors=k)
    scores = -cross_val_score(knn_model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
    rmse_scores.append(np.sqrt((scores).mean()))

best_k = ks[np.argmin(rmse_scores)]
print(f"best k = {best_k}") # best k = 12

best_knn = KNeighborsRegressor(n_neighbors=best_k)
best_knn.fit(X_train, y_train)
knn_pred = best_knn.predict(X_test)
rmse = round(root_mean_squared_error(y_test, knn_pred), 3)

print(f"root mean squared error of best KNN model: {rmse}")

plt.plot(ks, rmse_scores)
plt.xlabel("k")
plt.ylabel("RMSE with cross-validation")
plt.title("RMSE vs. k in KNN Hyperparameter Tuning")